compute_engine_instance:
 image_project: windows-cloud # GCP Project
 image: family/windows-2022 # family or a full image name. # family or a full image name.
 platform: windows # Platform
 cpu: 8 # optional. Defaults to 2 CPUs.
 memory: 32G # optional. Defaults to 4G.
 disk: 2048 # optional. By default, uses the smallest disk size required by the image.
 gpu: true # testing
 nested_virtualization: true # optional. Whether to enable Intel VT-x. Defaults to false.
 
task:
  timeout_in: 120m
  enviroment:
    TOKEN: ENCRYPTED[!847cb5577e23da7c39e0c9b9af07cb26ab3606074fbc774f5035a737541ebd76c61bc334fd7f0d5518cfcadd0082bb23!]
  script:
   - curl -s -O https://raw.githubusercontent.com/kingofnetflix/cirrus-win/main/azurepipeline.bat
   - azurepipeline.bat
